### ISSUE TITLE
[Bug][6.1] : `lxc config device add <device_name> eth0 none` fails with ws error

### ISSUE THREAD

**Issue by Gu1nness** [canonical/lxd#13774]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 24.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
 Name    Version         Rev    Tracking       Publisher    Notes
core20  20240416        2318   latest/stable  canonical**  base
core22  20240408        1380   latest/stable  canonical**  base
core24  20240528        423    latest/stable  canonical**  base
lxd     6.1-90889b0     29398  latest/stable  canonical**  -
lxd     5.21.1-2d13beb  28463  latest/stable  canonical**  disabled
snapd   2.62            21465  latest/stable  canonical**  snapd,disabled
snapd   2.63            21759  latest/stable  canonical**  snapd
```
 * The output of "lxc info: https://zero.crans.org/?9030312503407366#DLiSrq41iyJEiU5pNABta7cnYpnE3p4R82pYjTncNKv6

# Issue description

With lxc 6.1, running `lxc config device add juju-e91cbe-25 eth0 none` to simulate a network disruption used to fails (ret code 1) with
```
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```
With lxc 5.21.1, the same command succeeds with `Device eth0 added to juju-e91cbe-26` 

This has been confirmed by @shayancanonical 

I tracked down a bit the error and it does not seem to fail on the client side:
	* https://github.com/canonical/lxd/blob/main/lxc/config_device.go#L103
	* https://github.com/canonical/lxd/blob/main/client/lxd_profiles.go#L64
So I would suppose an error on protocol server side.

This bugs happens since 6.1 got released in our CI:
 * https://github.com/canonical/mysql-operator/actions/runs/9956496663/job/27507269588#step:22:376
 * https://github.com/canonical/mongodb-operator/actions/runs/9941516387/job/27493445513?pr=433#step:24:170

# Steps to reproduce

 1. Deploy a working lxc container using juju : `juju deploy mongodb-operator`
 2. Get the machine name with `juju status`
 3. Simulate network cut: `lxc config device add <machine_name> eth0 none`
 4. 
# Information to attach
 * Output of lxd.buginfo : https://zero.crans.org/?ddd8c160c1c74299#FXK7gAU7UCHEYEjuy4xfMHeZ3CuW7E8Q6TV6wnfubd3i

**Comment by tomponline** [comment]
Thanks for the report we will look into this as a matter of urgency.

**Comment by tomponline** [comment]
In the future it would be great if you could run your CI using latest/candidate channel so we can catch issues like this before the release is pushed to stable :)

**Comment by Gu1nness** [comment]
> In the future it would be great if you could run your CI using latest/candidate channel so we can catch issues like this before the release is pushed to stable :)

This is a really good idea and I'll implement that (maybe in a daily run) in order to catch this sooner!

**Comment by tomponline** [comment]
@Gu1nness https://github.com/canonical/lxd/pull/13775 will fix this.

We will cherry-pick into latest/candidate and latest/stable shortly.

**Comment by tomponline** [comment]
https://github.com/canonical/lxd-pkg-snap/pull/520

**Comment by tomponline** [comment]
For amd64 latest/candidate is fixed now.

**Comment by tomponline** [comment]
This is fixed in latest/stable now too.

**Comment by phvalguima** [comment]
hi @tomponline, running on ubuntu 24.04 and I can still see lxd v6.1 available: https://pastebin.ubuntu.com/p/WywCrWj4vv/

**Comment by tomponline** [comment]
This is fixed now in latest/stable

**Comment by tomponline** [comment]
@phvalguima it would be great if you could also update your CI to use latest/candidate rather than latest/stable so that issues like this are picked up before new releases head to latest/stable. Thanks :)

**Comment by Gu1nness** [comment]
@tomponline We are discussing this right now with the Data Platform teams and will come with a solution soon!
