### ISSUE TITLE
Image properties incorrectly taken from image in another project

### ISSUE THREAD

**Issue by markylaing** [canonical/lxd#16039]
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

22.04

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Local edge build (995a5bedbb)
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

`lxc image copy` gets image metadata before downloading the image file. If the fingerprint of the image is available locally, the local image is used instead. However, the image properties are copied from the local image rather than taken from the image metadata at the source.

Also, note that the output of `lxc image list --all-projects` is incorrect in the output below. We should see the same image fingerprint twice in the list. Once for each project containing the image.

cc @tomponline @kadinsayani 

### Steps to reproduce

```bash
$ lxc project list
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
|       NAME        | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |     DESCRIPTION     | USED BY |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
| default (current) | YES    | YES      | YES             | YES             | YES      | YES           | Default LXD project | 2       |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
mark@RUBIX:~/projects/canonical/lxd/test$ lxc image list
+-------+-------------+--------+-------------+--------------+------+------+-------------+
| ALIAS | FINGERPRINT | PUBLIC | DESCRIPTION | ARCHITECTURE | TYPE | SIZE | UPLOAD DATE |
+-------+-------------+--------+-------------+--------------+------+------+-------------+
$ lxc image copy images:alpine/3.20 local: --alias alpine
Image copied successfully!                   
$ lxc image show alpine | sed -e "s/description: .*/description: HELLO/" | lxc image edit alpine
$ lxc image show alpine
auto_update: false
properties:
  architecture: amd64
  description: HELLO
  os: Alpine
  release: "3.20"
  requirements.secureboot: "false"
  serial: "20250715_0016"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
$ lxc project create foo
Project foo created
$ lxc image copy images:alpine/3.20 local: --project foo --alias alpine
Image copied successfully!
$ lxc image show alpine --project foo
auto_update: false
properties:
  architecture: amd64
  description: HELLO
  os: Alpine
  release: "3.20"
  requirements.secureboot: "false"
  serial: "20250715_0016"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
$ lxc image list --all-projects
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+------------------------------+
| PROJECT | ALIAS  | FINGERPRINT  | PUBLIC | DESCRIPTION | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE          |
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+------------------------------+
| default | alpine | 9171d3242b42 | no     | HELLO       | x86_64       | CONTAINER | 3.09MiB | Jul 15, 2025 at 6:10pm (UTC) |
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+------------------------------+
```

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)

**Comment by nmezhenskyi** [comment]
> Also, note that the output of `lxc image list --all-projects` is incorrect in the output below.

@markylaing Should we open a separate issue for this?

It seems unrelated to image properties not being set correctly during copy.

I've made a fix to set image properties from source correctly in this PR https://github.com/canonical/lxd/pull/17546, but the `lxc image list --all-projects` output still needs to be addressed.

**Comment by tomponline** [comment]
> [@markylaing](https://github.com/markylaing) Should we open a separate issue for this?

If its wrong, yes please, and add it to the 26.04 milestone please

**Comment by markylaing** [comment]
> > [@markylaing](https://github.com/markylaing) Should we open a separate issue for this?
> 
> If its wrong, yes please, and add it to the 26.04 milestone please

🤦 I thought we had fixed this. I'll double check it.

**Comment by markylaing** [comment]
I can't find the PR but @kadinsayani and I fixed this a while back. Running the reproducer now on main I can see that the image description is not copied to the foo project and `lxc image list --all-projects` is returning the correct results:
```
mark.laing@canonical.com@work:~$ lxc image copy images:alpine/edge local:
Image copied successfully!                   
mark.laing@canonical.com@work:~$ lxc image list
+-------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |            DESCRIPTION            | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE         |
+-------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
|       | 126d2112f12c | no     | Alpine edge amd64 (20260204_0052) | x86_64       | CONTAINER | 3.27MiB | Feb 4, 2026 at 9:54am (UTC) |
+-------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
mark.laing@canonical.com@work:~$ lxc image alias create local:alpine 126d2112f12c
mark.laing@canonical.com@work:~$ lxc image show alpine | sed -e "s/description: .*/description: HELLO/" | lxc image edit alpine
mark.laing@canonical.com@work:~$ lxc project create foo
Project foo created
mark.laing@canonical.com@work:~$ lxc image copy images:alpine/3.20 local: --project foo --alias alpine
Image copied successfully!                   
mark.laing@canonical.com@work:~$ lxc image show alpine --project foo
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.20 amd64 (20260204_0052)
  os: Alpine
  release: "3.20"
  requirements.secureboot: "false"
  serial: "20260204_0052"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
mark.laing@canonical.com@work:~$ lxc image list --all-projects
+---------+--------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
| PROJECT | ALIAS  | FINGERPRINT  | PUBLIC |            DESCRIPTION            | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE         |
+---------+--------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
| default | alpine | 126d2112f12c | no     | HELLO                             | x86_64       | CONTAINER | 3.27MiB | Feb 4, 2026 at 9:54am (UTC) |
+---------+--------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
| foo     | alpine | 4954ad0a5bab | no     | Alpine 3.20 amd64 (20260204_0052) | x86_64       | CONTAINER | 3.09MiB | Feb 4, 2026 at 9:55am (UTC) |
+---------+--------+--------------+--------+-----------------------------------+--------------+-----------+---------+-----------------------------+
```

**Comment by nmezhenskyi** [comment]
@markylaing Oh yes, my bad. `lxc image list --all-projects` was fixed indeed. Here's the PR https://github.com/canonical/lxd/pull/14833.

~~I was just reproducing this incorrectly :)~~

**Comment by nmezhenskyi** [comment]
@markylaing Oh wait. In your last reproducer you used two different images (with different fingerprints) `images:alpine/edge` and `images:alpine/3.20`. The `lxc image list --all-projects` command handles this case correctly.

However, in your original reproducer (in the issue description) you've used the same image `images:alpine/3.20` for both projects.  I think this case is still not working correctly.

Here is my reproducer on the `main` branch:

```
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc project list
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
|       NAME        | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |     DESCRIPTION     | USED BY |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
| default (current) | YES    | YES      | YES             | YES             | YES      | YES           | Default LXD project | 17      |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------+---------+
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image list
+-------+-------------+--------+-------------+--------------+------+------+-------------+
| ALIAS | FINGERPRINT | PUBLIC | DESCRIPTION | ARCHITECTURE | TYPE | SIZE | UPLOAD DATE |
+-------+-------------+--------+-------------+--------------+------+------+-------------+
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image copy images:alpine/3.20 local: --alias alpine
Image copied successfully!                   
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image show alpine | sed -e "s/description: .*/description: HELLO/" | lxc image edit alpine
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image show alpine
auto_update: false
properties:
  architecture: amd64
  description: HELLO
  os: Alpine
  release: "3.20"
  requirements.secureboot: "false"
  serial: "20260204_0052"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc project create foo
Project foo created
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image copy images:alpine/3.20 local: --project foo --alias alpine
Image copied successfully!
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image show alpine --project foo
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.20 amd64 (20260204_0052)
  os: Alpine
  release: "3.20"
  requirements.secureboot: "false"
  serial: "20260204_0052"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
nikita-mezhenskyi@ndev:~/dev/lxd$ lxc image list --all-projects
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+-----------------------------+
| PROJECT | ALIAS  | FINGERPRINT  | PUBLIC | DESCRIPTION | ARCHITECTURE |   TYPE    |  SIZE   |         UPLOAD DATE         |
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+-----------------------------+
| default | alpine | 4954ad0a5bab | no     | HELLO       | x86_64       | CONTAINER | 3.09MiB | Feb 4, 2026 at 8:06pm (UTC) |
+---------+--------+--------------+--------+-------------+--------------+-----------+---------+-----------------------------+
```

The image fingerprint here is listed only once for the `default` project, but is missing for the `foo` project.  

This is incorrect, right? Or am I missing something?

**Comment by markylaing** [comment]
Eeeee how did I manage that 🤦‍♂️ 

Ok `lxc image list --all-projects` is still broken then. Can you please create a separate issue? Happy for it to be assigned to me. Thanks
